function [model, ranges, report] = computeFluxRanges(model, options)
%COMPUTEFLUXRANGES Compute reaction-wise feasible minima and maxima.
%
%   [MODEL, RANGES, REPORT] = fluto.computeFluxRanges(MODEL, OPTIONS)
%   uses COBRA Toolbox optimization for each reaction. Solver failures are
%   surfaced immediately instead of silently propagating invalid objective
%   values.
%
%   OPTIONS fields:
%     tolerance        numerical tolerance (default 1e-9)
%     removeBlocked    remove zero-range reactions (default true)
%     canonicalize     flip negative irreversible reactions (default true)
%     progressInterval print progress every N reactions, 0 disables (default 0)

    if nargin < 2 || isempty(options)
        options = struct();
    end
    options = localOptions(options);

    localRequireCobraFunctions();
    model = fluto.validateModel(model);

    nReactions = numel(model.rxns);
    minima = zeros(nReactions, 1);
    maxima = zeros(nReactions, 1);

    for i = 1:nReactions
        objectiveModel = changeObjective(model, model.rxns{i}, 1);

        minimumSolution = optimizeCbModel(objectiveModel, "min");
        maximumSolution = optimizeCbModel(objectiveModel, "max");

        minima(i) = localObjectiveValue( ...
            minimumSolution, ...
            model.rxns{i}, ...
            "minimum");
        maxima(i) = localObjectiveValue( ...
            maximumSolution, ...
            model.rxns{i}, ...
            "maximum");

        if minima(i) > maxima(i) + options.tolerance
            error( ...
                "fluto:InconsistentFluxRange", ...
                "Computed minimum exceeds maximum for reaction %s.", ...
                model.rxns{i});
        end

        if options.progressInterval > 0 ...
                && (mod(i, options.progressInterval) == 0 || i == nReactions)
            fprintf("FluTO FVA: %d/%d reactions complete\n", i, nReactions);
        end
    end

    model.lb = minima;
    model.ub = maxima;

    flipped = false(nReactions, 1);
    if options.canonicalize
        [model, flipped] = fluto.canonicalizeReactionDirections( ...
            model, ...
            options.tolerance);
    end

    ranges = table( ...
        model.rxnNumber, ...
        string(model.rxns), ...
        model.lb, ...
        model.ub, ...
        flipped, ...
        "VariableNames", ...
        {"ReactionNumber", "ReactionID", "Minimum", "Maximum", "DirectionFlipped"});

    blockedReport = struct( ...
        "blockedReactionIDs", strings(0, 1), ...
        "nBlockedReactions", 0, ...
        "removedMetaboliteIDs", strings(0, 1), ...
        "nRemovedMetabolites", 0);

    if options.removeBlocked
        [model, blockedReport] = fluto.removeBlockedReactions( ...
            model, ...
            options.tolerance);
    end

    report = struct( ...
        "nReactionsInput", nReactions, ...
        "nReactionsOutput", numel(model.rxns), ...
        "nDirectionFlipped", nnz(flipped), ...
        "blocked", blockedReport);
end

function options = localOptions(options)
    defaults = struct( ...
        "tolerance", 1e-9, ...
        "removeBlocked", true, ...
        "canonicalize", true, ...
        "progressInterval", 0);

    names = fieldnames(defaults);
    for i = 1:numel(names)
        name = names{i};
        if ~isfield(options, name)
            options.(name) = defaults.(name);
        end
    end

    validateattributes(options.tolerance, {'numeric'}, {'scalar', 'real', 'nonnegative', 'finite'});
    validateattributes(options.removeBlocked, {'logical', 'numeric'}, {'scalar'});
    validateattributes(options.canonicalize, {'logical', 'numeric'}, {'scalar'});
    validateattributes(options.progressInterval, {'numeric'}, {'scalar', 'integer', 'nonnegative'});
    options.removeBlocked = logical(options.removeBlocked);
    options.canonicalize = logical(options.canonicalize);
end

function localRequireCobraFunctions()
    required = ["changeObjective", "optimizeCbModel"];
    missing = required(arrayfun(@(name) exist(name, "file") ~= 2, required));
    if ~isempty(missing)
        error( ...
            "fluto:CobraDependencyMissing", ...
            "Missing COBRA Toolbox functions: %s", ...
            strjoin(missing, ", "));
    end
end

function value = localObjectiveValue(solution, reactionID, direction)
    if ~isstruct(solution) || ~isfield(solution, "f") || isempty(solution.f)
        error( ...
            "fluto:OptimizationFailed", ...
            "No %s objective value returned for reaction %s.", ...
            direction, ...
            reactionID);
    end

    if isfield(solution, "stat") && ~isempty(solution.stat) && solution.stat ~= 1
        error( ...
            "fluto:OptimizationFailed", ...
            "COBRA optimization status %g for %s of reaction %s.", ...
            double(solution.stat), ...
            direction, ...
            reactionID);
    end

    value = double(solution.f);
    if ~isscalar(value) || ~isfinite(value)
        error( ...
            "fluto:OptimizationFailed", ...
            "Non-finite %s objective value for reaction %s.", ...
            direction, ...
            reactionID);
    end
end
