function output = runCondition(model, condition, options)
%RUNCONDITION Run the maintained FluTO pipeline for one model condition.
%
%   OUTPUT = fluto.runCondition(MODEL, CONDITION, OPTIONS)
%
%   OPTIONS fields:
%     tolerance        numerical tolerance (default 1e-7)
%     computeRanges    whether to run reaction-wise FVA first (default true)
%     couplingOptions  options passed to buildFullyCoupledMatrix
%     tradeoffOptions  options passed to enumerateTradeoffs

    if nargin < 2 || isempty(condition)
        condition = struct();
    end
    if nargin < 3 || isempty(options)
        options = struct();
    end

    if ~isfield(options, "tolerance")
        options.tolerance = 1e-7;
    end
    if ~isfield(options, "computeRanges")
        options.computeRanges = true;
    end
    if ~isfield(options, "couplingOptions")
        options.couplingOptions = struct();
    end
    if ~isfield(options, "tradeoffOptions")
        options.tradeoffOptions = struct();
    end

    validateattributes(options.tolerance, {'numeric'}, {'scalar', 'real', 'positive', 'finite'});

    model = fluto.validateModel(model);
    model = fluto.applyCondition(model, condition);

    if logical(options.computeRanges)
        rangeOptions = struct( ...
            "tolerance", options.tolerance, ...
            "removeBlocked", true, ...
            "canonicalize", true, ...
            "progressInterval", 0);
        [model, fluxRanges, rangeReport] = fluto.computeFluxRanges( ...
            model, ...
            rangeOptions);
    else
        [model, ~] = fluto.canonicalizeReactionDirections( ...
            model, ...
            options.tolerance);
        fluxRanges = table( ...
            model.rxnNumber, ...
            string(model.rxns), ...
            model.lb, ...
            model.ub, ...
            "VariableNames", ...
            {"ReactionNumber", "ReactionID", "Minimum", "Maximum"});
        rangeReport = struct();
    end

    [model, fluxClassification] = fluto.classifyFluxes( ...
        model, ...
        options.tolerance);

    couplingOptions = options.couplingOptions;
    couplingOptions.tolerance = options.tolerance;
    [couplingMatrix, couplingDiagnostics] = ...
        fluto.buildFullyCoupledMatrix(model, couplingOptions);

    tradeoffResult = fluto.enumerateTradeoffs( ...
        model, ...
        couplingMatrix, ...
        options.tradeoffOptions);

    output = struct( ...
        "model", model, ...
        "fluxRanges", fluxRanges, ...
        "fluxClassification", fluxClassification, ...
        "rangeReport", rangeReport, ...
        "couplingMatrix", couplingMatrix, ...
        "couplingDiagnostics", couplingDiagnostics, ...
        "tradeoffResult", tradeoffResult);
end
